Fix bug where dropdown content was positioned in incorrectly on scrolling for first time
ankit-m/react-16-dropdown pull request #4
Opened 2018-11-30 10:01 UTC by Ghusar

2018-12-03 05:00 UTC, ankit-m commented
@Ghusar build is failing

2018-12-03 07:07 UTC, Ghusar commented
Should i commit package-lock.json also for resolving this build?

2019-01-03 09:24 UTC, ankit-m requested changes

2019-01-03 09:24 UTC, ankit-m commented on src/Dropdown.js
> +        triggerBoundingRect: updatedTriggerBoudingRect
No  need for new line

2019-01-03 09:24 UTC, ankit-m commented on src/Dropdown.js
> +    const currentTriggerBoundingRect = this.state.triggerBoundingRect || {};
You can simply set trigger rect in handler for opening the dropdown.

2019-01-07 09:22 UTC, ankit-m approved these changes

2019-01-07 09:23 UTC, merged